#!/usr/bin/env python3
"""Extract the original's front-end text: the instructions and the menu.

    .venv/bin/python tools/mkfront.py [--snap build/ce2.z80]

Writes src/data/front.6502 (committed; the build never runs this). Each
string is rendered onto a 32 x 24 grid as the Spectrum shows it (AT, newline
and the 32-column wrap; docs/research/frontend.md sections 1, 2 and 8), and
written out as lines the MODE 7 front end prints where they were:

    EQUB row, column, ink, paper : EQUS text : EQUB 0      ...   EQUB &FF

Row and column are the Spectrum's; the front end moves them right to make
room for MODE 7's colour codes. The instructions need the tape as loaded
(build/ce2.z80): the first room overwrites them.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from zx import Spectrum  # noqa: E402

# (label, address, format, attribute before the string): "rom" is RST &10's
# codes, "game" the game's own printer (&7E51): &00-&15 a sets the
# attribute. The redefine screen is filled with attribute 5 first (cyan).
STRINGS = [
    ("instr_title", 0x60C8, "rom", 7),
    ("instr_page1", 0x613C, "rom", 7),
    ("instr_page2", 0x6399, "rom", 7),
    ("menu_text", 0x9BF9, "game", 6),
    ("redefine_title", 0x9D0E, "game", 5),
    ("enter_name", 0x9E9B, "game", 7),
    ("hiscore_title", 0x9F44, "game", 6),
] + [(f"press_{i}", a, "game", 5) for i, a in enumerate(
    (0x9D34, 0x9D53, 0x9D72, 0x9D91, 0x9DB0, 0x9DCF, 0x9DEE, 0x9E0D))]


def render(m, addr, fmt, attr):
    """The cells a string sets: {(row, col): (char, attr)}."""
    cells = {}
    row = col = 0
    p = addr
    while True:
        c = m[p]
        p += 1
        if c == 0xFF:
            return cells
        if c == 0x16:
            row, col = m[p], m[p + 1]
            p += 2
        elif fmt == "game" and c <= 0x15:
            attr = m[p]
            p += 1
        elif fmt == "rom" and c == 0x0D:
            row, col = row + 1, 0
        elif fmt == "rom" and 0x10 <= c <= 0x15:
            p += 1
        elif c >= 0x20:
            if col == 32:
                row, col = row + 1, 0
            cells[(row, col)] = (c, attr)
            col += 1
        else:
            raise ValueError(f"&{addr:04X}: code &{c:02X} at &{p - 1:04X}")


# Lines the BBC front end leaves out (decision 13): it has no ZX Printer,
# and no joystick yet.
DROP = {"CAPS/SHIFT-P TO PRINTOUT", "JOYSTICK COMPATIBLE"}


def lines(cells):
    """Runs of cells on a row with one attribute, trailing blanks trimmed
    unless the paper shows them."""
    out = []
    for row in sorted({r for r, _ in cells}):
        cols = sorted(c for r, c in cells if r == row)
        run = []
        for col in cols:
            ch, attr = cells[(row, col)]
            if run and (col != run[-1][0] + 1 or attr != run[-1][2]):
                out.append((row, run))
                run = []
            run.append((col, ch, attr))
        out.append((row, run))
    result = []
    for row, run in out:
        text = "".join(chr(ch) for _, ch, _ in run)
        attr = run[0][2]
        if not attr & 0x38:
            text = text.rstrip()
        col = run[0][0]
        if text.startswith("\x7f"):
            # The ROM font's (C) at &7F: teletext has none, and to OSWRCH
            # &7F is DELETE.
            text, col = "(C)" + text[1:], col - 2
        if text and text not in DROP:
            result.append((row, col, attr & 7, (attr >> 3) & 7, text))
    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--snap", default="build/ce2.z80")
    ap.add_argument("--out", default="src/data/front.6502")
    args = ap.parse_args()
    m = Spectrum(args.snap).mem
    out = ["\\ Generated by tools/mkfront.py from the original: do not edit.", "",
           "\\ Each line: Spectrum row, column, ink, paper, then the text; &FF ends.", ""]
    for label, addr, fmt, attr in STRINGS:
        out.append(f".{label}             \\ &{addr:04X}")
        for row, col, ink, paper, text in lines(render(m, addr, fmt, attr)):
            esc = text.replace('"', '", 34, "')
            out.append(f'    EQUB {row:2d}, {col:2d}, {ink}, {paper} : EQUS "{esc}" : EQUB 0')
        out.append("    EQUB &FF")
    with open(args.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
