#!/usr/bin/env python3
"""Extract the original's sprites and their pointer tables.

    .venv/bin/python tools/mkgfx.py [--snap build/zx_start.z80]

Writes, committed (the build never runs this):
    src/data/sprites.bin    the sprite block &DFA2-&FDF7: Harry, the
                            monsters, truck, train and lifts
                            (docs/research/monsters.md, section 8), each
                            frame a column at a time
    src/data/gfx.6502       pointer tables into it, relocated to `sprites`
    src/data/monsters.bin   the monster table (&6B00, four 256-byte columns:
                            room, row, column, type)
    src/data/montypes.bin   the 52 monster types (&6F00, 4 bytes: ink, base
                            frame, flags, speed): docs/research/monsters.md,
                            section 3. (Apart, because it lives in page 3.)

A sprite frame is the original's: height in character rows, width in
bytes, then its pixels, 1 bit a pixel; but the pixels are stored a column
at a time (height*8 bytes for each byte across) where the original has a
row at a time (decision 20): the BBC draws a column at a time, and steps
down a column with an index alone (sprite.6502).
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from zx import Spectrum  # noqa: E402

SPRITES, SPRITES_END = 0xDFA2, 0xFDF8
HARRY_FRAMES = 0x89FF       # 12 pointers to frame headers
SPRITE_FRAMES = 0x91B7      # 152 pointers: monsters, truck, train, lifts
MONSTERS, MONTYPES, MONTYPES_END = 0x6B00, 0x6F00, 0x6FD0


def by_columns(block, offsets):
    """Each frame at these offsets in block, its rows made columns (frames
    one byte wide are the same either way). The frames don't overlap."""
    out = bytearray(block)
    for o in sorted(set(offsets)):
        h8, w = block[o] * 8, block[o + 1]
        pixels = block[o + 2:o + 2 + h8 * w]
        out[o + 2:o + 2 + h8 * w] = bytes(pixels[line * w + col] for col in range(w) for line in range(h8))
    return bytes(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--snap", default="build/zx_start.z80")
    ap.add_argument("--out", default="src/data")
    args = ap.parse_args()
    m = Spectrum(args.snap).mem
    word = lambda a: m[a] | m[a + 1] << 8
    frames = [word(HARRY_FRAMES + 2 * i) for i in range(12)] + [word(SPRITE_FRAMES + 2 * i) for i in range(152)]
    with open(f"{args.out}/sprites.bin", "wb") as f:
        f.write(by_columns(m[SPRITES:SPRITES_END], [p - SPRITES for p in frames]))

    def rel(ptr):
        assert SPRITES <= ptr < SPRITES_END, hex(ptr)
        return f"sprites + &{ptr - SPRITES:04X}"

    lines = [
        "\\ Generated by tools/mkgfx.py from the original: do not edit.",
        "",
        "\\ Harry's frames (&89FF), by facing + xf: 0-3 right, 4-7 left (shifted",
        "\\ 0/2/4/6 pixels, also the walk cycle), 8-11 climbing. Each points at",
        "\\ the frame's header (height in cells, width in bytes).",
        ".harry_frames",
    ]
    for i in range(12):
        lines.append(f"    EQUW {rel(word(HARRY_FRAMES + 2 * i))}")
    lines += [
        "",
        "\\ The other sprites' frames (&91B7): monsters, truck, train, lifts. A",
        "\\ monster type's base frame indexes this table.",
        ".sprite_frames",
    ]
    for i in range(152):
        lines.append(f"    EQUW {rel(word(SPRITE_FRAMES + 2 * i))}")
    with open(f"{args.out}/monsters.bin", "wb") as f:
        f.write(bytes(m[MONSTERS:MONTYPES]))
    with open(f"{args.out}/montypes.bin", "wb") as f:
        f.write(bytes(m[MONTYPES:MONTYPES_END]))
    with open(f"{args.out}/gfx.6502", "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"sprites.bin: {SPRITES_END - SPRITES} bytes")


if __name__ == "__main__":
    main()
