#!/usr/bin/env python3
"""Extract the original's objects ("things") as they are on the tape.

    .venv/bin/python tools/mkobjects.py [--snap build/ce2.z80]

From the snapshot taken as the tape finishes loading (nothing has run on
the tables yet). Writes, committed (the build never runs this):
    src/data/things.bin     the thing table &6600-&69FF: room (bit 7 = not
                            in the world), row, column, type, 256 each
    src/data/thinginit.bin  rooms, rows, columns of things 0-&28 (their
                            start, restored every egg)
    src/data/thingtypes.bin the 67 types &6A00-&6AC8: ink, graphic, kind
    src/data/visits.bin     the room-visit bonus &A380-&A3F8 (room 0-120)
    src/data/objgfx.bin     the object images &6FD0-&74B7, each a column
                            at a time (tools/mkgfx.py)
    src/data/objects.6502   the graphic pointers (&8A98, 73), relocated to
                            `objgfx`
See docs/research/objects.md.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from zx import Spectrum  # noqa: E402
from mkgfx import by_columns  # noqa: E402

THINGS, TYPES, TYPES_END = 0x6600, 0x6A00, 0x6AC9
VISITS, VISITS_END = 0xA380, 0xA3F9
OBJGFX, OBJGFX_END = 0x6FD0, 0x74B8
OBJ_POINTERS, OBJ_POINTER_COUNT = 0x8A98, 73


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--snap", default="build/ce2.z80")
    ap.add_argument("--out", default="src/data")
    args = ap.parse_args()
    m = Spectrum(args.snap).mem
    word = lambda a: m[a] | m[a + 1] << 8
    out = lambda name, a, b: open(f"{args.out}/{name}", "wb").write(bytes(m[a:b]))
    out("things.bin", THINGS, THINGS + 1024)
    # Where the 41 portable things start each egg (the original copies these
    # to &5B00 at start-up and back at every egg): rooms, rows, columns.
    open(f"{args.out}/thinginit.bin", "wb").write(
        bytes(m[THINGS:THINGS + 41] + m[THINGS + 256:THINGS + 256 + 41] + m[THINGS + 512:THINGS + 512 + 41]))
    out("thingtypes.bin", TYPES, TYPES_END)
    out("visits.bin", VISITS, VISITS_END)
    # The images a column at a time, as the sprites (tools/mkgfx.py).
    pointers = [word(OBJ_POINTERS + 2 * i) for i in range(OBJ_POINTER_COUNT)]
    open(f"{args.out}/objgfx.bin", "wb").write(by_columns(m[OBJGFX:OBJGFX_END], [p - OBJGFX for p in pointers]))
    lines = [
        "\\ Generated by tools/mkobjects.py from the original: do not edit.",
        "",
        "\\ The object graphics (&8A98): a type's graphic byte indexes this.",
        ".object_frames",
    ]
    for i in range(OBJ_POINTER_COUNT):
        p = word(OBJ_POINTERS + 2 * i)
        assert OBJGFX <= p < OBJGFX_END, hex(p)
        lines.append(f"    EQUW objgfx + &{p - OBJGFX:04X}")
    open(f"{args.out}/objects.6502", "w").write("\n".join(lines) + "\n")
    print("things: 1024, types:", TYPES_END - TYPES, "visits:", VISITS_END - VISITS,
          "graphics:", OBJGFX_END - OBJGFX)


if __name__ == "__main__":
    main()
