#!/usr/bin/env python3
"""Extract the room data and tile font from the original, and choose each
room's four colours.

    .venv/bin/python tools/mkrooms.py [--snap shots/zx_start.z80]

Writes, all committed (the build never runs this):
    src/data/roomdata.bin   the original's room data, &AA5C-&DFA1, verbatim
    src/data/tiles.bin      the tile font, codes &20-&5B (8 bytes each)
    src/data/roomoffsets.txt  where each room starts in roomdata.bin
                            (tools/packrooms.py reads it)
    src/data/rooms.6502     each room's palette

The palette (decision 2): MODE 1 shows four colours, so each room gets the
four that cover most of its pixels, with the room's background paper as
logical colour 0, yellow as logical 3 (decision 6: Harry is yellow), and
every Spectrum colour mapped to one of the four. The
mapping is chosen by brute force to show the most pixels in their own
colour, under two hard rules: in every cell the room draws, ink and paper
must stay different; and every colour but the background must differ from
the background, so anything drawn later in any colour stays visible.
Pixel counts come from the oracle (tools/zxrooms.py, build/rooms).
"""
import argparse
import itertools
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from zx import Spectrum  # noqa: E402

ROOM_PTRS = 0xA96A
DATA_START, DATA_END = 0xAA5C, 0xDFA2
CHARS = 0x73B8
FIRST_TILE, LAST_TILE = 0x20, 0x5B
NAMES = "black blue red magenta green cyan yellow white".split()
# Spectrum colour order is GRB-ish (0 black, 1 blue, 2 red, 3 magenta, 4 green,
# 5 cyan, 6 yellow, 7 white); the BBC's physical colours are RGB bits
# (0 black, 1 red, 2 green, 3 yellow, 4 blue, 5 magenta, 6 cyan, 7 white).
ZX_TO_BBC = [0, 4, 1, 5, 2, 6, 3, 7]
# Colours the room data doesn't use still get drawn (sprites, items), so
# every colour carries a little weight, to send an unused colour to its
# nearest neighbour rather than to any free slot.
PRIOR = [20] * 8
RGB = [(0, 0, 0), (0, 0, 215), (215, 0, 0), (215, 0, 215),
       (0, 215, 0), (0, 215, 215), (215, 215, 0), (215, 215, 215)]


def dist(a, b):
    """Perceptual-ish distance between two Spectrum colours."""
    (r1, g1, b1), (r2, g2, b2) = RGB[a], RGB[b]
    return ((r1 - r2) * 0.30) ** 2 + ((g1 - g2) * 0.59) ** 2 + ((b1 - b2) * 0.11) ** 2


def room_usage(r, rooms_dir):
    """Pixel weight per colour, and the (paper, ink) pairs that need telling
    apart, from the oracle's picture of room r (rows 2-23)."""
    d = open(f"{rooms_dir}/room_{r:03d}.bin", "rb").read()
    scr, attrs = d[:6144], d[6144:6912]
    weight = list(PRIOR)
    pairs = set()
    for row in range(2, 24):
        for col in range(32):
            a = attrs[row * 32 + col]
            ink, paper = a & 7, (a >> 3) & 7
            on = 0
            for line in range(8):
                y = row * 8 + line
                on += bin(scr[((y & 0xC0) << 5) + ((y & 7) << 8) + ((y & 0x38) << 2) + col]).count("1")
            weight[paper] += 64 - on
            weight[ink] += on
            if on and on < 64 and ink != paper:
                pairs.add((paper, ink))
    return weight, pairs


YELLOW = 6


def choose_palette(bg, weight, pairs):
    """Returns (colours: four Spectrum colours, logical 0 first; cmap: the
    logical colour for each Spectrum colour 0-7). Yellow is always one of
    the four (decision 6): Harry is yellow."""
    best = None
    others = [c for c in range(8) if c not in (bg, YELLOW)]
    for pair in itertools.combinations(others, 2):
        colours = [bg, *pair, YELLOW] if bg != YELLOW else [bg, *pair, 7]
        rest = [c for c in range(8) if c not in colours]
        for choice in itertools.product(range(4), repeat=len(rest)):
            cmap = [0] * 8
            for i, c in enumerate(colours):
                cmap[c] = i
            for c, l in zip(rest, choice):
                cmap[c] = l
            if any(cmap[c] == 0 for c in range(8) if c != bg):
                continue
            if any(cmap[p] == cmap[i] for p, i in pairs):
                continue
            cost = sum(weight[c] * dist(c, colours[cmap[c]]) for c in range(8))
            if best is None or cost < best[0]:
                best = (cost, colours, cmap)
    if best is None:
        raise RuntimeError("no palette satisfies the rules")
    return best[1], best[2]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--snap", default="build/zx_start.z80")
    ap.add_argument("--rooms", default="build/rooms")
    ap.add_argument("--out", default="src/data")
    args = ap.parse_args()
    m = Spectrum(args.snap).mem
    os.makedirs(args.out, exist_ok=True)

    with open(f"{args.out}/roomdata.bin", "wb") as f:
        f.write(bytes(m[DATA_START:DATA_END]))
    with open(f"{args.out}/tiles.bin", "wb") as f:
        f.write(bytes(m[CHARS + 8 * FIRST_TILE:CHARS + 8 * (LAST_TILE + 1)]))

    lines = [
        "\\ Generated by tools/mkrooms.py from the original: do not edit.",
        "",
    ]
    offsets = []
    for r in range(121):
        if r == 0:
            offsets.append(0)
            continue
        p = m[ROOM_PTRS + 2 * r] | m[ROOM_PTRS + 2 * r + 1] << 8
        offsets.append(p - DATA_START)
    with open(f"{args.out}/roomoffsets.txt", "w") as f:
        f.write("\n".join(str(o) for o in offsets[1:]) + "\n")
    lines += [
        "\\ Each room's palette (decision 2), four bytes: the BBC physical colours",
        "\\ of logical 0-3 a nibble each (low nibble first), then the logical",
        "\\ colour of each Spectrum colour 0-7, two bits each (colour 0 lowest).",
        ".room_palettes",
    ]
    report = []
    for r in range(1, 121):
        bg = (m[DATA_START + offsets[r]] >> 3) & 7
        weight, pairs = room_usage(r, args.rooms)
        colours, cmap = choose_palette(bg, weight, pairs)
        phys = [ZX_TO_BBC[c] for c in colours]
        packed = [phys[0] | phys[1] << 4, phys[2] | phys[3] << 4,
                  cmap[0] | cmap[1] << 2 | cmap[2] << 4 | cmap[3] << 6,
                  cmap[4] | cmap[5] << 2 | cmap[6] << 4 | cmap[7] << 6]
        lines.append(f"    EQUB {', '.join(f'&{b:02X}' for b in packed)}"
                     f"   \\ {r:3d}: {' '.join(NAMES[c] for c in colours)}; map {''.join(map(str, cmap))}")
        exact = sum(weight[c] for c in colours) / sum(weight)
        report.append((exact, r, colours, cmap))
    with open(f"{args.out}/rooms.6502", "w") as f:
        f.write("\n".join(lines) + "\n")
    report.sort()
    mean = sum(e for e, *_ in report) / len(report)
    print(f"palettes: {100 * mean:.2f}% of pixels in their own colour on average; worst:")
    for e, r, colours, cmap in report[:5]:
        subs = ", ".join(f"{NAMES[c]}->{NAMES[colours[cmap[c]]]}" for c in range(8) if c not in colours)
        print(f"  room {r:3d} {100 * e:5.1f}%  [{' '.join(NAMES[c] for c in colours)}]  {subs}")


if __name__ == "__main__":
    main()
